"""Add fields to Sale model for enhanced sale flow

Revision ID: 3c9d6e2f1a4b
Revises: fa8bc33f5b41
Create Date: 2026-05-15 18:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c9d6e2f1a4b'
down_revision = 'fa8bc33f5b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('status', sa.String(length=20), server_default='abierta', nullable=False))
    op.add_column('sales', sa.Column('numero_personas', sa.Integer(), server_default='1', nullable=False))
    op.add_column('sales', sa.Column('comentarios', sa.Text(), nullable=True))
    op.add_column('sales', sa.Column('descuento_tipo', sa.String(length=20), nullable=True))
    op.add_column('sales', sa.Column('descuento_valor', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('descuento_monto', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('total_paid', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('camarero_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['camarero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'camarero_id')
    op.drop_column('sales', 'total_paid')
    op.drop_column('sales', 'descuento_monto')
    op.drop_column('sales', 'descuento_valor')
    op.drop_column('sales', 'descuento_tipo')
    op.drop_column('sales', 'comentarios')
    op.drop_column('sales', 'numero_personas')
    op.drop_column('sales', 'status')
    # ### end Alembic commands ###
