"""Add SiteConfig model for branding configuration

Revision ID: abc123def456
Revises: add_biometric_check_in_system
Create Date: 2026-05-21 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = 'add_biometric_check_in_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Table already exists in database, this is a documentation migration
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op downgrade since table creation was a no-op
    pass
    # ### end Alembic commands ###
