"""Add SiteConfig model for branding configuration

Revision ID: abc123def456
Revises: add_biometric_check_in_system
Create Date: 2026-05-21 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = 'add_biometric_check_in_system'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'site_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('logo_path', sa.String(255), nullable=True),
        sa.Column('banner_background_path', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_config')
    # ### end Alembic commands ###
